brew "anomalyco/tap/opencode", trusted: true
brew "btop"
brew "diff-so-fancy"
brew "difftastic"
brew "fd"
brew "gh"
brew "git"
brew "gnupg"
brew "jq"
brew "lazygit"
brew "lf"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree-sitter-cli"
brew "yq"
brew "zoxide"

brew "fnm"
brew "node"
brew "libpq"

brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "qemu"

brew "cloudflared"
brew "fluxcd/tap/flux", trusted: true
brew "hashicorp/tap/terraform", trusted: true
brew "k3d"
brew "k9s"
brew "kubernetes-cli"

brew "acsandmann/tap/rift", trusted: true, restart_service: :changed
cask "cyberduck"
cask "gcloud-cli"
cask "ghostty"
cask "google-chrome"
cask "slack"
cask "tableplus"

brew "jadx"
brew "openjdk"
brew "python@3.14"
cask "android-commandlinetools"
cask "charles"
cask "mitmproxy"
cask "http-toolkit"
cask "nomachine"
cask "xquartz"
