"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind $stashed)](cyan) "
conflicted = "󠀠"
untracked = "󠀠"
modified = "󠀠"
staged = "󠀠"
renamed = "󠀠"
deleted = "󠀠"
stashed = "≡"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
