#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Kirill Vakalov"
email = "102545999+kirillvakalov@users.noreply.github.com"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
