git:
  paging:
    externalDiffCommand: difft --color=always --syntax-highlight=off

gui:
  theme:
    inactiveBorderColor:
      - ''
    selectedLineBgColor:
      - ''
  authorColors:
    '*': 'blue'
